### ISSUE TITLE
Create virtual network with Address space from IPAM

### ISSUE THREAD

**Issue by ceza-tech** [Azure-Terraform/terraform-azurerm-virtual-network#58]
I would like to create virtual networks using IP address space allocated from Azure IPAM (Preview) 

![image](https://github.com/user-attachments/assets/4bec3d03-842d-43d6-aac1-11aacf9b696d)

**Comment by fabiendelpierre** [comment]
Hi there,

This Terraform module is one that we develop and use for our internal company use, but have chosen to share publicly in accordance with the included license. Since we don't currently use Azure IPAM, and if supporting Azure IPAM would require a code change to this module, we won't do it, sorry.

However, I spent a few minutes researching how to do this with Terraform and it appears you wouldn't need to make any changes to this module. See the following link for a code example: https://blog.nashtechglobal.com/ipam-reservation-and-vnet-subnet-integration-with-terraform/
